[project]
name = "modern-chat"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=45.0.3",
    "textual>=3.2.0",
    "websockets>=15.0.1",
]
